server:
  port: 9000
spring:
  cloud:
    discovery:
      enabled: false
eureka:
  client:
    enabled: false
---
spring:
  profiles: prod
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    enabled: true
#---
#spring:
#  profiles: kafka
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: farewell-topic
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

